# Generated by Django 5.0 on 2024-02-05 16:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('World', 'World'), ('Business', 'Business'), ('Technology', 'Technology')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
